/* Generated by Opal 0.10.5 */
(function(Opal) {
  var $a, $b, TMP_1, self = Opal.top, $scope = Opal, nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice, $module = Opal.module, $klass = Opal.klass;

  Opal.add_stubs(['$ready?', '$render', '$Home', '$[]', '$H1', '$on', '$alert', '$BUTTON']);
  ($a = ($b = $scope.get('Document'))['$ready?'], $a.$$p = (TMP_1 = function(){var self = TMP_1.$$s || this, $c, $d, TMP_2;

  return ($c = ($d = $scope.get('Element')['$[]']("#content")).$render, $c.$$p = (TMP_2 = function(){var self = TMP_2.$$s || this;

    return $scope.get('Components').$Home()}, TMP_2.$$s = self, TMP_2.$$arity = 0, TMP_2), $c).call($d)}, TMP_1.$$s = self, TMP_1.$$arity = 0, TMP_1), $a).call($b);
  return (function($base) {
    var $Components, self = $Components = $module($base, 'Components');

    var def = self.$$proto, $scope = self.$$scope;

    (function($base, $super) {
      function $Home(){};
      var self = $Home = $klass($base, $super, 'Home', $Home);

      var def = self.$$proto, $scope = self.$$scope, $a, $b, TMP_3;

      return ($a = ($b = self).$render, $a.$$p = (TMP_3 = function(){var self = TMP_3.$$s || this, $c, $d, TMP_4, $e, TMP_5, $f, $g, TMP_6;

      ($c = ($d = self).$H1, $c.$$p = (TMP_4 = function(){var self = TMP_4.$$s || this;

        return "I am here"}, TMP_4.$$s = self, TMP_4.$$arity = 0, TMP_4), $c).call($d);
        return ($c = ($e = ($f = ($g = self).$BUTTON, $f.$$p = (TMP_6 = function(){var self = TMP_6.$$s || this;

        return "Press me"}, TMP_6.$$s = self, TMP_6.$$arity = 0, TMP_6), $f).call($g)).$on, $c.$$p = (TMP_5 = function(){var self = TMP_5.$$s || this;

        return self.$alert("yes")}, TMP_5.$$s = self, TMP_5.$$arity = 0, TMP_5), $c).call($e, "click");}, TMP_3.$$s = self, TMP_3.$$arity = 0, TMP_3), $a).call($b, $scope.get('DIV'))
    })($scope.base, (($scope.get('Hyperloop')).$$scope.get('Component')))
  })($scope.base);
})(Opal);
